python example_noshare_test_time.py --dataset_type='CTF_OmniClusterSelected_th48_26cluster' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --batch_size=64
python example_noshare_test_time.py --dataset_type='mars-science-laboratory' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --batch_size=64
python example_noshare_test_time.py --dataset_type='soil-moisture-active-passive' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --lr=1e-4 --batch_size=64
python example_noshare_test_time.py --dataset_type='server-machine-dataset' --train_type='效率实验' --epochs=50 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --batch_size=64
python example_noshare_test_time.py --dataset_type='application-server-dataset' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --batch_size=64
python example_noshare_test_time.py --dataset_type='yidong-22' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --batch_size=64

python example_noshare_test_time.py --dataset_type='water-distribution' --train_type='效率实验' --epochs=1 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --lr=1e-4 --batch_size=64
python example_noshare_test_time.py --dataset_type='secure-water-treatment' --train_type='效率实验' --epochs=1 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --lr=1e-4 --batch_size=64
# python example_noshare_test_time.py --dataset_type='soil-moisture-active-passive' --train_type='效率实验' --epochs=100 --seed=2021 --out_dir=0523 --gpu_id=0 --base_model_dir=test --min_std=0.01 --model_dim=200 --lr=5e-4 --batch_size=64